/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class APK_SUHU extends javax.swing.JFrame {
    double SUHUAWAL,KONVERSIKE; 

    /**
     * Creates new form APK_SUHU
     */
    public APK_SUHU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        T_SUHU_AWAL = new javax.swing.JTextField();
        tskala_asal = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        tskalatujuan = new javax.swing.JComboBox<>();
        b_hasil_konversi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        vhasil = new javax.swing.JLabel();
        breset = new javax.swing.JButton();
        tclose = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KONVERSI SUHU");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SUHU AWAL"));

        T_SUHU_AWAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_SUHU_AWALActionPerformed(evt);
            }
        });

        tskala_asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celcius", "kelvin", "fahrenheit" }));
        tskala_asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tskala_asalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T_SUHU_AWAL)
                    .addComponent(tskala_asal, 0, 232, Short.MAX_VALUE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T_SUHU_AWAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tskala_asal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("KONVERSI KE"));

        tskalatujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celcius", "kelvin", "fahrenheit" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tskalatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tskalatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        b_hasil_konversi.setText("KONVERSI");
        b_hasil_konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hasil_konversiActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("HASIL"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        vhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(vhasil, java.awt.BorderLayout.CENTER);

        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        tclose.setText("CLOSE");
        tclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_hasil_konversi)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(breset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(tclose)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_hasil_konversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset)
                    .addComponent(tclose))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_hasil_konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hasil_konversiActionPerformed
        // TODO add your handling code here:
    // Mendapatkan nilai suhu awal dari input teks
    double suhuAwal;
    try {
        suhuAwal = Double.parseDouble(T_SUHU_AWAL.getText());
    } catch (NumberFormatException e) {
        // Jika inputan tidak valid, tampilkan pesan kesalahan dan hentikan eksekusi
        vhasil.setText("Masukkan angka yang valid!");
        return;
    }
    
    // Mendapatkan skala asal dan tujuan dari combo box
    String skalaAwal = tskala_asal.getSelectedItem().toString();
    String skalaTujuan = tskalatujuan.getSelectedItem().toString();
    
    // Memanggil method konversiSuhu untuk melakukan konversi
    double hasilKonversi = konversiSuhu(suhuAwal, skalaAwal, skalaTujuan);
    
    // Menampilkan hasil konversi
    vhasil.setText(String.valueOf(hasilKonversi));
}    

// Method untuk konversi suhu
private double konversiSuhu(double suhuAwal, String skalaAwal, String skalaTujuan) {
    double hasilKonversi = 0;
    if (skalaAwal.equals("celcius")) {
        if (skalaTujuan.equals("celcius")) {
            hasilKonversi = suhuAwal;
        } else if (skalaTujuan.equals("kelvin")) {
            hasilKonversi = suhuAwal + 273.15;
        } else if (skalaTujuan.equals("fahrenheit")) {
            hasilKonversi = (suhuAwal * 9 / 5) + 32;
        }
    } else if (skalaAwal.equals("kelvin")) {
        if (skalaTujuan.equals("celcius")) {
            hasilKonversi = suhuAwal - 273.15;
        } else if (skalaTujuan.equals("kelvin")) {
            hasilKonversi = suhuAwal;
        } else if (skalaTujuan.equals("fahrenheit")) {
            hasilKonversi = (suhuAwal - 273.15) * 9 / 5 + 32;
        }
    } else if (skalaAwal.equals("fahrenheit")) {
        if (skalaTujuan.equals("celcius")) {
            hasilKonversi = (suhuAwal - 32) * 5 / 9;
        } else if (skalaTujuan.equals("kelvin")) {
            hasilKonversi = (suhuAwal - 32) * 5 / 9 + 273.15;
        } else if (skalaTujuan.equals("fahrenheit")) {
            hasilKonversi = suhuAwal;
        }
    }
    return hasilKonversi;
    }//GEN-LAST:event_b_hasil_konversiActionPerformed

    private void tskala_asalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tskala_asalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tskala_asalActionPerformed

    private void T_SUHU_AWALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_SUHU_AWALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_SUHU_AWALActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        // Mengosongkan inputan
    T_SUHU_AWAL.setText("");
    vhasil.setText("");
    }//GEN-LAST:event_bresetActionPerformed

    private void tcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcloseActionPerformed
        // TODO add your handling code here:
         // Menutup program
    System.exit(0);
    }//GEN-LAST:event_tcloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APK_SUHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APK_SUHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APK_SUHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APK_SUHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APK_SUHU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T_SUHU_AWAL;
    private javax.swing.JButton b_hasil_konversi;
    private javax.swing.JButton breset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tclose;
    private javax.swing.JComboBox<String> tskala_asal;
    private javax.swing.JComboBox<String> tskalatujuan;
    private javax.swing.JLabel vhasil;
    // End of variables declaration//GEN-END:variables
}